services:
  app:
    image: node:18-alpine
    command: sh -c "yarn install && yarn run dev"
    ports:
      - 127.0.0.1:3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      PGHOST: postgresql
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDB: postgres
  postgresql:
    image: postgres:14.0
    volumes:
      - todo-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATABASE: postgres

volumes:
  todo-postgres-data:
